# Generated by Django 5.2.1 on 2025-06-03 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_buyer_profile_username_and_more'),
        ('checkout', '0002_alter_order_view_user_alter_shipping_address_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buyer_Profile',
        ),
        migrations.DeleteModel(
            name='Vendor_Profile',
        ),
    ]
