# Generated by Django 5.2.3 on 2025-07-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
