# Generated by Django 5.2.3 on 2025-07-08 12:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_newsletter_approved'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='publisher',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='publisher',
            field=models.ManyToManyField(limit_choices_to={'role': 'publisher'}, related_name='newsletters_pub', to=settings.AUTH_USER_MODEL),
        ),
    ]
