# Generated by Django 5.2.3 on 2025-07-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_remove_newsletter_publisher_newsletter_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='description',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsletter',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/'),
        ),
    ]
