# Generated by Django 5.2.3 on 2025-07-10 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_newsletter_description_newsletter_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='journalist',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='journalist',
            field=models.ForeignKey(default=1, limit_choices_to={'role': 'journalist'}, on_delete=django.db.models.deletion.CASCADE, related_name='newsletters_jour', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
