# Generated by Django 5.2.3 on 2025-07-10 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0005_remove_newsletter_journalist_newsletter_journalist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'permissions': (('newsletter_create', 'Can create newsletter'), ('newsletter_list', 'Can view newsletters'), ('newsletter_update', 'Can update newsletter'), ('newsletter_delete', 'Can delete newsletter'))},
        ),
    ]
