# Generated by Django 5.2.3 on 2025-06-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('editors', models.ManyToManyField(limit_choices_to={'role': 'editor'}, related_name='editor_pub', to='accounts.customuser')),
                ('journalist', models.ManyToManyField(limit_choices_to={'role': 'journalist'}, related_name='journalist_pub', to='accounts.customuser')),
            ],
        ),
    ]
