# Generated by Django 5.2.3 on 2025-06-26 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('editors', models.ManyToManyField(limit_choices_to={'role': 'editor'}, related_name='editor_publishers', to='accounts.customuser')),
                ('journalists', models.ManyToManyField(limit_choices_to={'role': 'journalist'}, related_name='journalist_publishers', to='accounts.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journalist', models.ManyToManyField(limit_choices_to={'role': 'journalist'}, related_name='articles', to='accounts.customuser')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='article.publisher')),
            ],
        ),
    ]
