# Generated by Django 5.2.3 on 2025-07-07 11:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='editors',
            field=models.ManyToManyField(limit_choices_to={'position': 'editor'}, related_name='article_editors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='journalist',
            field=models.ManyToManyField(limit_choices_to={'position': 'journalist'}, related_name='articles_journalists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='editors',
            field=models.ManyToManyField(limit_choices_to={'position': 'editor'}, related_name='editor_publishers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='journalists',
            field=models.ManyToManyField(limit_choices_to={'position': 'journalist'}, related_name='journalist_publishers', to=settings.AUTH_USER_MODEL),
        ),
    ]
