# Generated by Django 5.2.3 on 2025-07-09 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_article_description_article_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='journalist',
        ),
        migrations.AddField(
            model_name='article',
            name='journalist',
            field=models.ForeignKey(blank=True, limit_choices_to={'position': 'journalist'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles_journalist', to=settings.AUTH_USER_MODEL),
        ),
    ]
