# Generated by Django 5.2.3 on 2025-07-10 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_remove_article_journalist_article_journalist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': (('article_create', 'Can create article'), ('article_list', 'Can view articles'), ('article_update', 'Can update article'), ('article_delete', 'Can delete article'))},
        ),
    ]
