# Generated by Django 5.2.1 on 2025-06-18 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_buyer_profile_delete_vendor_profile'),
        ('vendors', '0004_alter_store_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vendors.store'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='store',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='accounts.user_profile'),
        ),
    ]
