# Generated by Django 5.2.3 on 2025-06-26 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('article', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('newsletter', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='article_independently',
            field=models.ManyToManyField(blank=True, related_name='journalist_articles', to='newsletter.newsletter'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='custom_user_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='newsletter_independently',
            field=models.ManyToManyField(blank=True, related_name='journalist_newsletters', to='article.article'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscriptions_journalists',
            field=models.ManyToManyField(blank=True, limit_choices_to={'position': 'journalist'}, related_name='subscribers_journalists', to='accounts.customuser'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscriptions_publishers',
            field=models.ManyToManyField(blank=True, related_name='subscribers_publishers', to='accounts.customuser'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_set', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='resettoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
