# Generated by Django 5.2.3 on 2025-07-04 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_info_product_cart_user'),
        ('vendors', '0005_alter_product_store_alter_store_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='info_product_cart',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vendors.product'),
            preserve_default=False,
        ),
    ]
